using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VehicleRentalManager.Models;
using VehicleRentalManager.Services;
using VehicleRentalManager.Repositories;

namespace VehicleRentalManager.Controllers;

[ApiController]
[Route("auth")]
public class AuthController : ControllerBase
{
    private readonly IJwtTokenService _jwtTokenService;
    private readonly IUserRepository _userRepository;

    public AuthController(
        IJwtTokenService jwtTokenService,
        IUserRepository userRepository)
    {
        _jwtTokenService = jwtTokenService;
        _userRepository = userRepository;
    }

    /// <summary>
    /// Starts the Google OAuth flow (login + registration).
    /// The user will be redirected to Google and then back to GoogleCallback.
    /// </summary>
    [HttpGet("login-google")]
    public IActionResult LoginWithGoogle(string? returnUrl = "/auth")
    {
        // returnUrl is where the user will be redirected after we finish authentication
        var props = new AuthenticationProperties
        {
            RedirectUri = Url.Action("GoogleCallback", "Auth", new { returnUrl })
        };

        // This sends the user to Google for authentication
        return Challenge(props, GoogleDefaults.AuthenticationScheme);
    }

    /// <summary>
    /// Handles the callback from Google after the user consents.
    /// Here we:
    /// 1) Read the Google user info (email, name).
    /// 2) Look up the user in the database by email.
    /// 3) If the user does not exist, create a new one (registration).
    /// 4) Generate a JWT for this user.
    /// 5) Redirect back to the frontend with the token and basic user info.
    /// </summary>
    [HttpGet("google-callback")]
    public async Task<IActionResult> GoogleCallback(string? returnUrl = "/auth")
    {
        // At this point, ASP.NET Core has already validated Google's response
        var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);

        if (!result.Succeeded || result.Principal == null)
        {
            return Redirect("/auth?error=login_failed");
        }

        var principal = result.Principal;

        // Get email and name from the Google identity
        var email = principal.FindFirst(ClaimTypes.Email)?.Value;
        var name = principal.Identity?.Name ?? email ?? "Unknown";

        if (string.IsNullOrEmpty(email))
        {
            // If Google did not return an email, you can decide how to handle this
            return Redirect("/auth?error=email_not_found");
        }

        // 1) Try to find the user in the database by email
        // NOTE: IUserRepository will be implemented when the database is ready.
        var user = await _userRepository.GetByEmailAsync(email);

        if (user == null)
        {
            // 2) User does not exist yet: create a new user (registration)
            user = new User
            {
                // Id will be generated by the database in the real implementation
                Email = email,
                Name = name
                // Other properties (CreatedAt, etc.) can be set here when available
            };

            user = await _userRepository.CreateAsync(user);
        }

        // 3) Generate a JWT for this user
        var jwt = _jwtTokenService.GenerateToken(user);

        // 4) Redirect back to the frontend with the token and basic info
        var encodedToken = Uri.EscapeDataString(jwt);
        var encodedName = Uri.EscapeDataString(user.Name);
        var encodedEmail = Uri.EscapeDataString(user.Email);

        var redirectUrl = $"{returnUrl}?token={encodedToken}&name={encodedName}&email={encodedEmail}";

        return Redirect(redirectUrl);
    }

    /// <summary>
    /// Signs out the current user (cookie-based logout).
    /// This does not invalidate the JWT, only the server-side cookie.
    /// </summary>
    [Authorize]
    [HttpPost("logout")]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return Ok();
    }

    /// <summary>
    /// Returns basic information about the current authenticated user.
    /// This uses the server-side principal (cookies or JWT, depending on configuration).
    /// </summary>
    [Authorize]
    [HttpGet("me")]
    public IActionResult GetCurrentUser()
    {
        var user = HttpContext.User;

        var email = user.FindFirst(ClaimTypes.Email)?.Value;
        var name = user.Identity?.Name;

        return Ok(new
        {
            name,
            email,
            isAuthenticated = user.Identity?.IsAuthenticated ?? false
        });
    }
}
